apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
# This defines which pods are going to be represented by this service.
# the service becomes an endpoint for other services or for external users to connect to 
  selector:
    app: webapp


  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
# This defines which pods are going to be represented by this service.
# the service becomes an endpoint for other services or for external users to connect to 
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort